info:
  app:
    name: My catalog
    description: description
    version: 1.0.0

spring:
  application:
    name: catalog
  boot:
    admin:
      url: http://catalog_admin:8081
      #url: http://localhost:8081

management:
  security:
    enabled: false

endpoints:
  prometheus:
      path: "prometheus-metrics"
